# Generated by Django 4.2.7 on 2024-03-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_default_town_or_city_userprofile_default_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_email',
        ),
    ]
